Repository ITU-BDSA2024-GROUP13/Chirp, pull requests merged in 2024-10, with the labels that each got.

#121 Onion refactor
  Chirp.sln
  exe
  main
  src/Chirp.Core/Chirp.Core.csproj
  src/Chirp.Core/MessageDTO.cs
  src/Chirp.Razor/Model/DBFacade.cs
  src/Chirp.Razor/Program.cs
  src/Chirp.Repositories/CheepViewModel.cs
  src/Chirp.Repositories/Chirp.Repositories.csproj
  src/Chirp.Repositories/DBFacade.cs
  src/Chirp.Repositories/HelperFunctions.cs
  src/Chirp.Repositories/IMessageRepository.cs
  src/Chirp.Repositories/MessageRepository.cs
  src/Chirp.Repositories/data/chirps.db
  src/Chirp.Repositories/data/schema.sql
  src/Chirp.Services/CheepService.cs
  src/Chirp.Services/Chirp.Services.csproj
  src/Chirp.Services/ICheepService.cs
  src/Chirp.Web/Chirp.Web.csproj
  src/Chirp.Web/Pages/Public.cshtml
  src/Chirp.Web/Pages/Shared/_Layout.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml
  src/Chirp.Web/Program.cs
  src/Chirp.Web/Properties/launchSettings.json
  src/Chirp.Web/Public.cshtml.cs
  src/Chirp.Web/UserTimeline.cshtml.cs
  src/Chirp.Web/appsettings.Development.json
  src/Chirp.Web/appsettings.json
  src/Chirp.Web/wwwroot/css/style.css
  src/Chirp.Web/wwwroot/favicon/favicon.ico
  src/Chirp.Web/wwwroot/images/arrow.png
  src/Chirp.Web/wwwroot/images/icon1.png
Labels: refactor

#133 Release yaml
  .github/workflows/main_bdsagroup013chirprazor.yml
  .github/workflows/release.yaml
Labels: bug

#134 Fixed bug that lead to wrong pagination in navbar
  src/Chirp.Web/Public.cshtml.cs
Labels: bug

#153 New chirp design MAJOR
  src/Chirp.Web/Pages/Public.cshtml
  src/Chirp.Web/Pages/Shared/_Layout.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml
  src/Chirp.Web/Public.cshtml.cs
  src/Chirp.Web/Razor/Public.cshtml.cs
  src/Chirp.Web/Razor/UserTimeline.cshtml.cs
  src/Chirp.Web/wwwroot/css/style.css
  src/Chirp.Web/wwwroot/images/arrow.png
  src/Chirp.Web/wwwroot/images/filter.png
Labels: enhancement
